GET http://localhost:3001/api/questions HTTP/1.1
###
GET http://localhost:3001/api/questions/1/answers HTTP/1.1
###
POST http://localhost:3001/api/answers HTTP/1.1
Content-Type: application/json

{
    "text": "Text of the new answer",
    "respondent": "Bob",
    "score": 0,
    "date": "2024-05-06",
    "questionId": 1
}

